---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    labels:
      - dependencies
      - python
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /    
    labels:
      - dependencies
      - docker
    schedule:
      interval: daily

